/**
 * Where an uploaded picture goes, and how to tell a real one apart later.
 *
 * Locally there is a disk, and writing to public/uploads is the simplest thing
 * that works. On Vercel there is no disk: the filesystem is read-only, and even
 * where it is writable each request may land on a different machine, so a file
 * written during the upload would be gone by the time the page asked for it.
 * That is why listing photos already on the site survive — they are committed
 * to the repository and shipped with the build — while anything uploaded after
 * a deploy quietly disappeared.
 *
 * So: blob storage when a token is configured, disk otherwise. One switch, in
 * one place, because every picture on the site goes through /api/upload.
 */

import { writeFile, mkdir } from "fs/promises";
import { join } from "path";
import { put } from "@vercel/blob";

/** Blob storage is in play only once Vercel has handed us a token. */
export function blobConfigured(): boolean {
  return Boolean(process.env.BLOB_READ_WRITE_TOKEN);
}

/**
 * Saves the bytes and returns the URL to show them at.
 *
 * `filename` is generated by the caller — never taken from the upload, which
 * is how "../../.env" and "evil.php" get written.
 */
export async function storeUpload(
  buffer: Buffer,
  filename: string,
  contentType: string,
): Promise<string> {
  if (blobConfigured()) {
    const blob = await put(`uploads/${filename}`, buffer, {
      access: "public",
      contentType,
      // The name already carries a UUID; without this the store adds a second
      // random suffix and the URL stops being predictable from the filename.
      addRandomSuffix: false,
      cacheControlMaxAge: 31_536_000,
    });
    return blob.url;
  }

  const dir = join(process.cwd(), "public", "uploads");
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, filename), buffer);
  return `/uploads/${filename}`;
}

/** A local upload: /uploads/<uuid>.<ext>, and nothing clever in between. */
const LOCAL = /^\/uploads\/[A-Za-z0-9._-]+$/;

/** Vercel's own blob hosts. Anything else is somebody else's server. */
const BLOB_HOST = /^[a-z0-9-]+\.public\.blob\.vercel-storage\.com$/;

/**
 * Whether a URL is a picture this site issued.
 *
 * Worth being strict about wherever the answer is stored and shown to somebody
 * else — an abuse report is read by an administrator, so an off-site URL in one
 * would be a way of pointing them at a server of the reporter's choosing.
 */
export function isUploadedImageUrl(url: string): boolean {
  const clean = url.trim();
  if (clean.includes("..")) return false;
  if (LOCAL.test(clean)) return true;

  try {
    const u = new URL(clean);
    return u.protocol === "https:" && BLOB_HOST.test(u.hostname);
  } catch {
    return false;                     // not absolute, and not a local path
  }
}
